### ISSUE TITLE
Green on green

### ISSUE THREAD

**Issue by AverageMarcus** [jsoxford/hack#2]
![image](https://cloud.githubusercontent.com/assets/3384072/24191894/1d1b1314-0ee5-11e7-8e5c-2a05e03adea1.png)

**Comment by omgmog** [comment]
already pointed out to @benfoxall 👍 

Also we should get some vendor prefixes on the `blend-mode` properties to ensure it works on all _green_ browsers.

**Comment by AverageMarcus** [comment]
Ah good. So the background colour is going to be set to green, yeah?

**Comment by omgmog** [comment]
Totally fixed in 74ea04889f94bb45fc5ea8909a54ded5bad75449

**Comment by AverageMarcus** [comment]
Oh? 
![image](https://cloud.githubusercontent.com/assets/3384072/24196939/8ebd0178-0ef7-11e7-9295-26accaabdda2.png)

**Comment by benfoxall** [comment]
yeah - good shout.  I think I've got an idea of how to make this work (worst case we can just make the headings black text).  I'll plonk it in now

**Comment by AverageMarcus** [comment]
Either change one of the greens or stick a semi-transparent background on the text block?

**Comment by benfoxall** [comment]
@AverageMarcus I've just pushed this up 

![image](https://cloud.githubusercontent.com/assets/51385/24197811/11370e16-0efb-11e7-83b9-5e903384c2f6.png)

**Comment by AverageMarcus** [comment]
Love it! 💯

**Comment by benfoxall** [comment]
Ace!
