### ISSUE TITLE
Hack Guides

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/hack#4]
This hack is going to be an open "whatever you want to build in 4 hours".  With each attendee/team working on their own hack and showing it at the end.

Though we'd also like to give an option for people who want a head start or help with a particular hack topic/idea.

This is where *Hack Guides* come in.

As a Hack Guide, you'll help a group of people by supplying them with a template to hack on (this might be a fork-able repo on github, or jsbin example that can be cloned).  Then you'll take your group through the technology, helping with their ideas or answering any questions as they go on.

* We'll probably limit groups to 5 (unless you'd rather fewer/more)
* Each attendee in your group would work & present individually as they would have before (you're not making one big team)
* You're welcome to hack too!

Some example Hack Guides:

* I'm Lisa - I'll bring an aFrame template and google cardboards so you can create some virtual reality experiences.
* I'm Fred - I'll get you started with a Phaser.JS platform game, you'll be able to design new levels and add sound effects
* I'm Sarah - I'll show you how to receive text messages to your WebApp
* I'm Jill - Interested in chatbots?  I'll bring along my slack bot and show you how to add your own commands.

### The important bit…
# We're looking for Hack Guides at Render Hack

If there's something that you think would be fun for attendees, and that you'd be happy to lead a small group though - get in touch! Either comment in here, or drop be a message/dm on `@benjaminbenben`.

Some things:
* the hack is from 6pm till 10pm on Thursday Night (after the first day of the conference)
* you'll have a great time
* it'll be great for attendees
* it'll be a great way to show attendees something that you're interested in
* we'll get you up on the render hack site
* it'll be fun
* you'll get free food
* if you're not attending Render - we should be able to get you an evening pass for this

**Comment by AverageMarcus** [comment]
I'd prob do something around chatbots. Need to have a think how we could do that as:
1) They're meant to be demoing a URL at the end
2) Need a slack team to work with and enough integration slots (Could set one up)

On another note, I've been wanting to look into browser based image detection and tracking. Might come up with something along those lines.

***UPDATE***

I'm Marcus - Interested in chatbots? I'll bring along my slack bot and show you how to add your own commands.
Example slackbot: https://github.com/jsoxford/RenderHack-ExampleBot
Test Slack team: https://renderconfhack.herokuapp.com/

**Comment by omgmog** [comment]
I'd like to do something with VR, and A-Frame is probably the easiest way to do it. 

**Multi-user VR experiences with A-Frame**

I can base my template on the examples in [this tutorial](https://github.com/haydenjameslee/networked-aframe/blob/master/docs/Tutorial:%20Create%20your%20first%20Networked-Aframe%20experience.md)

I'll bring along some Google Cardboard v1 headsets (@benfoxall have you got any of those Google Cardboard v2 headsets going spare?) and I've got some A-Frame resources that I put together for the [gamedevday.club](http://gamedevday.club/) hack-day last summer... (may need to update them to the newest A-Frame, but that's fine!)

A-Frame released a nice tutorial for beginners: https://aframe.io/aframe-school/

And for anybody _local_ to Oxford, I can promote the [Oxford's Virtual Reality Crowd](https://www.meetup.com/Oxfords-Virtual-Reality-Crowd/) meetup group! 😃

**Comment by gfwilliams** [comment]
I could do something with:

* Lending 5 people Puck.js devices 
* Lending 5 people Espruino WiFi boards and those Nokia LCD displays (or potentially the LED light string if I have enough).

I also have some individual things (a plotter, or an Espruino word clock) but I'm not sure how we'd get a group to share those such that they could demo individually at the end.

I guess I could just bring 5 Espruino-powered contraptions an people could fight over them?

**Comment by sammachin** [comment]
I can do something with Nexmo and our Call Control Object language so you can write a simple JSON _script_ which you can then cal via a phone.
Or if people are more interested I can also show them how to build their first Alexa Skill and test it with a virtual echo in a web browser

**Comment by AverageMarcus** [comment]
@sammachin add you as a guide: https://github.com/jsoxford/hack/blob/master/_guides/sammachin.md

Feel free to edit as needed

**Comment by benfoxall** [comment]
@sammachin awesome!  I guess NCCO stuff would be cool - would be nice to have some of the conference sponsor's tech along.

Shall I update your entry? https://github.com/jsoxford/hack/blob/master/_guides/sammachin.md I guess some text along the lines of:

> I'll show you how to get started with receiving calls in a browser using Nexmo's NCCO language.

---

@gfwilliams great! I added an entry for you too: https://github.com/jsoxford/hack/blob/master/_guides/gfwilliams.md 

It's completely up to you - I guess the main limiting factor is how tight we are on time (3.5h), so maybe something where people have something working from the start?  I've got a couple of light strings too if you want them to add in?

Let me know, and I can update your entry (or just throw in a PR if you want)

---

@omgmog Do you want to update your description/content to be a bit more chatty? Something like

> I'll bring along a few google cardboards, and provide you with a template to get started with a-frame.

**Comment by omgmog** [comment]
~I'll get on it.~ Done!

**Comment by gfwilliams** [comment]
Ok, great - @benfoxall you have 2 strings set up with Pucks already?
