### ISSUE TITLE
Prizes

### ISSUE THREAD

**Issue by benfoxall** [jsoxford/hack#6]
> [There’ll probably definitely be prizes.](http://jsoxford.com/hack/)

We're looking for any prizes for hack attendees.  These don't have to be big or expensive - just kinda nice mementos or cool things for attendees of the hack day.

Having said that - if you want to award hacks that you particularly dig, that's totally fine too (it'll be pretty easy to do this on the second day as we'll have a big list of all the submissions).

Depending on what stuff we get, we might go for:
* a set of things for each person as they present
* a kitty of swag/stuff that they can choose from after they present
* (as mentioned above), giving out the day after

So,  if anyone has any prixes that they think would work, then let us know. Stuff like:

* spare stickers you've got lying around
* google cardboards that you've found
* a raspberry Pi that you've never managed to use
* (sponsors) interesting swag/prizes that you've got
* (sponsors) any bigger prizes that you'd like to award

Either comment on here - or drop me a mail at benfoxall@gmail.com if there's something that you'd like to add.  We'll get them listed on the hack site for attendees too.

**Comment by AverageMarcus** [comment]
> a kitty of swag/stuff that they can choose from after they present
uhh... what?

* I have a big pile of stickers that can be given away. A couple JSOxford ones too I think.
* I could 3D print some little logos if I get time (Maybe the Render and JSOxford logos?)
